on:
  workflow_call:
    inputs:
      soc:
        required: true
        type: string
      target:
        required: true
        type: string
      project:
        required: true
        type: string

name: Smoke Test (workflow call)

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build ${{inputs.soc}}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install target
        uses: dtolnay/rust-toolchain@v1
        with:
          target: ${{ inputs.target}}
          toolchain: stable
          components: rust-src

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.7.5

      - name: Build example
        run: cd .github/test-projects/${{inputs.project}} && ./build.sh ${{inputs.soc}} ${{inputs.target}}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.soc}}
          path: .github/test-projects/${{inputs.project}}/output/${{inputs.soc}}




#  run:
#    runs-on: [ "self-hosted", "linux", "ARM64", "smoke-tester-2" ]
#    needs: build
#
#    strategy:
#      matrix: *build-matrix
#
#
#    steps:
#      #- uses: actions/download-artifact@v4
#      #  with:
#      #    name: probe-rs
#
#      - name: Checkout sources
#        uses: actions/checkout@v4
#
#      - name: Run embedded-tests
#        run: |
#          python ${ORCHESTRATOR} --target ${{inputs.soc}} --step-executor ./.github/test-projects/step-executor.sh